# 集群名称
brokerClusterName=DefaultCluster
# broker 名称
brokerName=broker-a
# broker id
brokerId=0
# 集群角色
brokerRole=ASYNC_MASTER
# 刷盘方式
flushDiskType=ASYNC_FLUSH

deleteWhen=04
# 存储时间
fileReservedTime=48
# 是否自动创建 topic
autoCreateTopicEnable=true
# 是否自动创建订阅组
autoCreateSubscriptionGroup=true
